[project]
name = "BuildArena"
version = "2.0.2"
description = "Text-interface for BuildArena"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "imageio-ffmpeg>=0.6.0",
    "mcp[cli]>=1.23.1",
    "numpy-quaternion>=2024.0.8",
    "Pillow>=10.0.0",
    "python-fcl>=0.7.0.8",
    "tqdm>=4.67.0",
    "trimesh>=4.6.10",
]
