"""Load real game collider + visual transform data from dump TOML.

The TOML is generated by running the ColliderDumper mod in Besiege once.
The loader looks in:
1) ``COLLIDER_DUMP_PATH`` when configured
2) ``.local/collider_dump.toml`` (project-local)

Each block entry can contain:
- ``colliders``: Unity primitive colliders (box/sphere/capsule/mesh metadata)
- ``visuals``: Mesh transform entries extracted from prefab hierarchy
"""
from __future__ import annotations

import tomllib
from pathlib import Path
from typing import Any

import numpy as np
import quaternion as nq
import trimesh

from .paths import get_block_registry_path, get_collider_dump_path

# ── path-keyed caches (dict mutation, no ``global`` needed) ───────────
_dump_cache: dict[str, dict[int, dict[str, Any]]] = {}
_shape_root_cache: dict[str, dict[int, dict[str, list[float]]]] = {}

# ── half-grid snapping ────────────────────────────────────────────────
# Conceptual block dimensions in Besiege are always multiples of 0.5
# (1x1 grid cells with half-cell substeps). Collider geometry, however,
# is intentionally inset/offset for clearance (e.g. 0.95 instead of 1.0
# for AddPoint slabs, 0.319 vs 0.5 for the wheel's tread thickness).
# We round inferred bounds and face centers to the nearest 0.5 multiple
# so the displayed coordinates match the conceptual grid the user
# expects to see in the simulator.
_HALF_GRID = 0.5


def _snap_value_to_half(*, value: float) -> float:
    """Round a scalar to the nearest 0.5 multiple."""
    return round(float(value) / _HALF_GRID) * _HALF_GRID


def _snap_vector_to_half(*, vector: np.ndarray) -> np.ndarray:
    """Round each component of a 3-vector to the nearest 0.5 multiple."""
    return np.asarray(
        [_snap_value_to_half(value=float(item)) for item in vector],
        dtype=np.float64,
    )


def _find_dump_path() -> Path | None:
    return get_collider_dump_path()


_DEFAULT_DUMP_PATH: Path | None = _find_dump_path()


def _sort_table_items(table: dict[str, Any]) -> list[tuple[str, Any]]:
    def _sort_key(item: tuple[str, Any]) -> tuple[int, str]:
        key, _value = item
        suffix = key[1:] if len(key) > 1 else key
        if suffix.isdigit():
            return (0, int(suffix))
        return (1, key)

    return sorted(table.items(), key=_sort_key)


def load_dump(*, dump_path: Path | None = None) -> dict[int, dict[str, Any]]:
    """Load and cache the collider dump.

    Parameters
    ----------
    dump_path : Path | None
        Explicit path to ``collider_dump.toml``.  Falls back to the
        auto-discovered default when *None*.
    """
    resolved_path = get_collider_dump_path(dump_path=dump_path or _DEFAULT_DUMP_PATH)

    cache_key = str(resolved_path.resolve())
    if cache_key in _dump_cache:
        return _dump_cache[cache_key]

    with open(resolved_path, "rb") as f:
        data = tomllib.load(f)

    result: dict[int, dict[str, Any]] = {}
    blocks = data.get("blocks", {})
    for block_id_str, block_data in blocks.items():
        block_id = int(block_id_str)
        colliders_table = block_data.get("colliders", {})
        visuals_table = block_data.get("visuals", {})

        collider_list: list[dict[str, Any]] = []
        for _coll_key, coll in _sort_table_items(colliders_table):
            collider_list.append(coll)

        visual_list: list[dict[str, Any]] = []
        for _visual_key, visual in _sort_table_items(visuals_table):
            visual_list.append(visual)

        meta_probe = block_data.get("meta_probe", {})

        result[block_id] = {
            "name": block_data.get("name", ""),
            "colliders": collider_list,
            "visuals": visual_list,
            "meta_probe": meta_probe,
        }

    _dump_cache[cache_key] = result
    return result


def has_real_colliders(*, dump_path: Path | None = None) -> bool:
    return get_collider_dump_path(dump_path=dump_path or _DEFAULT_DUMP_PATH).is_file()


def get_colliders_for_block(*, block_id: int, dump_path: Path | None = None) -> list[dict[str, Any]] | None:
    """Return the list of raw collider dicts for a given block ID, or None."""
    dump = load_dump(dump_path=dump_path)
    block_entry = dump.get(block_id)
    if block_entry is None:
        return None
    colliders = block_entry.get("colliders", [])
    if len(colliders) == 0:
        return None
    return colliders


def get_dump_block_name(*, block_id: int, dump_path: Path | None = None) -> str | None:
    """Return raw dump block name for a given ID, or None."""
    dump = load_dump(dump_path=dump_path)
    block_entry = dump.get(block_id)
    if block_entry is None:
        return None
    block_name = str(block_entry.get("name", "")).strip()
    if block_name == "":
        return None
    return block_name


def get_all_dump_blocks(*, dump_path: Path | None = None) -> dict[int, str]:
    """Return {block_id: camel_case_name} for every block in the dump."""
    dump = load_dump(dump_path=dump_path)
    result: dict[int, str] = {}
    for block_id, entry in dump.items():
        name = str(entry.get("name", "")).strip()
        if name != "":
            result[block_id] = name
    return result


def infer_shape_root_from_dump(*, block_id: int, dump_path: Path | None = None) -> dict[str, list[float]] | None:
    """Infer shape/root from solid collider bounds in local space.

    Returns ``{"shape": [x, y, z], "root": [x, y, z]}`` or None when missing.
    """
    resolved_dump_path = get_collider_dump_path(dump_path=dump_path or _DEFAULT_DUMP_PATH)
    path_key = str(resolved_dump_path.resolve())
    cache = _shape_root_cache.setdefault(path_key, {})
    if block_id in cache:
        return cache[block_id]

    colliders = get_colliders_for_block(block_id=block_id, dump_path=dump_path)
    if colliders is None:
        return None

    parts: list[trimesh.Trimesh] = []
    for collider in colliders:
        if bool(collider.get("is_trigger", False)):
            continue
        if _is_noise_collider(collider=collider):
            continue
        collider_mesh = _build_collider_from_dump(collider=collider)
        if collider_mesh is not None:
            parts.append(collider_mesh)

    if len(parts) == 0:
        return None

    combined = trimesh.util.concatenate(parts)
    if combined.bounds is None:
        return None

    bounds_min = np.asarray(combined.bounds[0], dtype=np.float64)
    bounds_max = np.asarray(combined.bounds[1], dtype=np.float64)

    snapped_min = _snap_vector_to_half(vector=bounds_min)
    snapped_max = _snap_vector_to_half(vector=bounds_max)
    # If snapping collapses an axis (extent < grid), keep the raw extent
    # so we never emit zero-thickness shape components.
    raw_extent = bounds_max - bounds_min
    snapped_extent = snapped_max - snapped_min
    for axis_index in range(3):
        if snapped_extent[axis_index] < 1e-6 and raw_extent[axis_index] > 1e-6:
            snapped_min[axis_index] = bounds_min[axis_index]
            snapped_max[axis_index] = bounds_max[axis_index]

    shape = (snapped_max - snapped_min).tolist()
    root = ((snapped_min + snapped_max) * 0.5).tolist()

    inferred = {
        "shape": [float(v) for v in shape],
        "root": [float(v) for v in root],
    }
    cache[block_id] = inferred
    return inferred


def get_visuals_for_block(*, block_id: int, dump_path: Path | None = None) -> list[dict[str, Any]] | None:
    """Return raw visual transform entries for a block ID, or None."""
    dump = load_dump(dump_path=dump_path)
    block_entry = dump.get(block_id)
    if block_entry is None:
        return None
    visuals = block_entry.get("visuals", [])
    if len(visuals) == 0:
        return None
    return visuals


def get_visual_transform(*, block_id: int, dump_path: Path | None = None) -> dict[str, Any] | None:
    """Return the primary visual transform for a block.

    Selection strategy:
    1) Filter out known non-render/auxiliary nodes.
    2) Prefer nodes in `Vis` hierarchy and with renderer.
    3) Prefer transform paths that end with `/Vis`.
    4) Prefer visual nodes closest to solid collider centroid.
    """
    visuals = get_visuals_for_block(block_id=block_id, dump_path=dump_path)
    if visuals is None:
        return None

    colliders = get_colliders_for_block(block_id=block_id, dump_path=dump_path) or []
    solid_centers: list[np.ndarray] = []
    for collider in colliders:
        if bool(collider.get("is_trigger", False)):
            continue
        if _is_noise_collider(collider=collider):
            continue
        try:
            solid_centers.append(_collider_center_local(collider=collider))
        except Exception:
            continue
    solid_centroid = np.mean(solid_centers, axis=0) if len(solid_centers) > 0 else None

    def _is_visual_noise(*, visual: dict[str, Any]) -> bool:
        path = str(visual.get("transform_path", "")).lower()
        obj = str(visual.get("object_name", "")).lower()
        mesh_name = str(visual.get("mesh_name", "")).lower()
        text = " ".join([path, obj, mesh_name])
        if "directionarrow" in text:
            return True
        if "pendingdestructionsim" in text:
            return True
        return False

    candidates = [visual for visual in visuals if not _is_visual_noise(visual=visual)]
    if len(candidates) == 0:
        candidates = visuals

    def _visual_center_local(visual: dict[str, Any]) -> np.ndarray:
        return np.asarray(visual.get("local_position", [0, 0, 0]), dtype=np.float64)

    def _score(visual: dict[str, Any]) -> tuple[int, int, int, float]:
        in_vis = bool(visual.get("in_vis_hierarchy", False))
        has_renderer = bool(visual.get("has_renderer", False))
        path = str(visual.get("transform_path", ""))
        ends_with_vis = path.endswith("/Vis") or path == "Vis"
        if solid_centroid is not None:
            distance = float(np.linalg.norm(_visual_center_local(visual) - solid_centroid))
        else:
            distance = float(np.linalg.norm(_visual_center_local(visual)))

        return (
            0 if in_vis else 1,
            0 if has_renderer else 1,
            0 if ends_with_vis else 1,
            distance,
        )

    best = min(candidates, key=_score)
    return {
        "local_scale": best.get("local_scale", [1, 1, 1]),
        "local_rotation": best.get("local_rotation", [1, 0, 0, 0]),
        "local_translation": best.get("local_position", [0, 0, 0]),
        "transform_path": best.get("transform_path", ""),
        "mesh_name": best.get("mesh_name", ""),
    }


def _collider_center_local(*, collider: dict[str, Any]) -> np.ndarray:
    local_position = np.asarray(collider.get("local_position", [0, 0, 0]), dtype=np.float64)
    local_scale = np.asarray(collider.get("local_scale", [1, 1, 1]), dtype=np.float64)
    center = np.asarray(collider.get("center", [0, 0, 0]), dtype=np.float64)
    rot_mat = _rotation_matrix_from_wxyz(local_rotation=collider.get("local_rotation", [1, 0, 0, 0]))
    return rot_mat @ (center * local_scale) + local_position


def _is_add_point_collider(*, collider: dict[str, Any]) -> bool:
    if not collider.get("enabled", True):
        return False
    layer_name = str(collider.get("layer_name", "")).lower()
    layer_id = int(collider.get("layer", -1))
    if not (layer_name.startswith("addpoint") or layer_id in (12, 14)):
        return False
    if bool(collider.get("is_trigger", False)):
        go = str(collider.get("gameobject_name", "")).lower()
        if go == "joint":
            size = collider.get("size", [1, 1, 1])
            if len(size) == 3:
                dims = [abs(float(s)) for s in size]
                max_dim = max(dims)
                min_dim = min(dims)
                if max_dim > 1e-6 and min_dim / max_dim > _JOINT_TRIGGER_DIM_RATIO:
                    return False
    return True


def _is_joint_trigger_collider(*, collider: dict[str, Any]) -> bool:
    if not bool(collider.get("is_trigger", False)):
        return False
    layer_name = str(collider.get("layer_name", "")).lower()
    layer_id = int(collider.get("layer", -1))
    if layer_name == "jointtrigger" or layer_id == 22:
        return True
    behaviour_types = collider.get("behaviour_types", [])
    if isinstance(behaviour_types, list):
        for type_name in behaviour_types:
            if "triggersetjoint" in str(type_name).lower():
                return True
    return False


def _is_noise_collider(*, collider: dict[str, Any]) -> bool:
    pending_tag = str(collider.get("tag", "")).lower()
    gameobject_name = str(collider.get("gameobject_name", "")).lower()
    transform_path = str(collider.get("transform_path", "")).lower()
    behaviour_types = [str(b).lower() for b in collider.get("behaviour_types", []) or []]
    haystack = " ".join([pending_tag, gameobject_name, transform_path] + behaviour_types)
    if "waterplane" in haystack:
        return True
    if "explosion" in haystack:
        return True
    if "brokenvis" in haystack:
        return True

    if _is_add_point_collider(collider=collider) or _is_joint_trigger_collider(collider=collider):
        return False

    if "pendingdestructionsim" in haystack:
        return True
    if "directionarrow" in haystack:
        return True
    return False


def _block_is_enabled(*, block_id: int, block_name: str) -> bool:
    if "unused" in str(block_name).lower():
        return False

    try:
        from .definitions_loader import load_runtime_blocks
        blocks = load_runtime_blocks()
    except Exception:
        return True

    if block_name in blocks:
        return bool(blocks[block_name].get("enabled", True))

    return True


_FACE_AREA_THRESHOLD = 1e-4
_FACE_AREA_RATIO_THRESHOLD = 0.25
_FACE_POS_TOLERANCE = 0.15
_FACE_NORMAL_THRESHOLD = -0.9
_JOINT_TRIGGER_DIM_RATIO = 0.5
_AXIS_ALIGNED_THRESHOLD = 0.95
_DIRECTIONAL_ADDPOINT_THIN_RATIO = 0.5
_STEERING_HINGE_END_ONLY_BLOCK_IDS = frozenset({28})
_HINGE_MIDPOINT_SIDE_BLOCK_IDS = frozenset({5})
_FULL_CUBE_ADDPOINT_BLOCK_IDS = frozenset({30})
_NO_ADDPOINT_FACE_BLOCK_IDS = frozenset({101})


def _enumerate_box_faces(
    *,
    collider: dict[str, Any],
) -> list[tuple[np.ndarray, np.ndarray]]:
    """Return (face_center, face_normal) in block-local space for each
    non-degenerate face of a box collider.

    Thin-slab colliders (e.g. wheel axle addpoints) have edge faces whose
    area is negligible compared to the main surface.  These edge faces are
    suppressed via a relative-area ratio filter so that only the meaningful
    attachment surfaces survive.
    """
    local_position = np.asarray(
        collider.get("local_position", [0, 0, 0]), dtype=np.float64
    )
    local_scale = np.asarray(
        collider.get("local_scale", [1, 1, 1]), dtype=np.float64
    )
    center = np.asarray(collider.get("center", [0, 0, 0]), dtype=np.float64)
    size = np.asarray(collider.get("size", [1, 1, 1]), dtype=np.float64)
    rot_mat = _rotation_matrix_from_wxyz(
        local_rotation=collider.get("local_rotation", [1, 0, 0, 0])
    )

    scaled_center = center * local_scale
    half_ext = size * np.abs(local_scale) * 0.5

    face_specs: list[tuple[int, float]] = []
    for axis in range(3):
        perp_axes = [a for a in range(3) if a != axis]
        face_area = half_ext[perp_axes[0]] * half_ext[perp_axes[1]] * 4.0
        if face_area < _FACE_AREA_THRESHOLD:
            continue
        face_specs.append((axis, face_area))

    max_area = max((a for _, a in face_specs), default=0.0)

    faces: list[tuple[np.ndarray, np.ndarray]] = []
    for axis, face_area in face_specs:
        if max_area > _FACE_AREA_THRESHOLD and face_area < max_area * _FACE_AREA_RATIO_THRESHOLD:
            continue
        for sign_val in (1.0, -1.0):
            offset = np.zeros(3)
            offset[axis] = sign_val * half_ext[axis]
            face_center = rot_mat @ (scaled_center + offset) + local_position
            normal_local = np.zeros(3)
            normal_local[axis] = sign_val
            face_normal = rot_mat @ normal_local
            if float(np.max(np.abs(face_normal))) < _AXIS_ALIGNED_THRESHOLD:
                continue
            faces.append((face_center, face_normal))
    return faces


def _select_outward_named_addpoint_faces(
    *,
    collider: dict[str, Any],
    faces: list[tuple[np.ndarray, np.ndarray]],
    solid_centroid: np.ndarray | None,
) -> list[tuple[np.ndarray, np.ndarray]]:
    """Collapse directional AddPoint_* boxes to their single outward plane.

    Some Besiege prefabs model named add points (for example
    ``AddPoint_Top``) as shallow boxes instead of zero-thickness sheets.
    Enumerating every large face from that box can expose side faces that
    are placement helpers, not buildable attachment planes.
    """
    if len(faces) <= 1:
        return faces

    layer_name = str(collider.get("layer_name", "")).strip().lower()
    if layer_name != "addpoint":
        return faces
    if solid_centroid is None:
        return faces

    size = np.asarray(collider.get("size", [1, 1, 1]), dtype=np.float64)
    local_scale = np.asarray(collider.get("local_scale", [1, 1, 1]), dtype=np.float64)
    extents = np.abs(size * local_scale)
    max_extent = float(np.max(extents))
    min_extent = float(np.min(extents))
    if max_extent <= 1e-9:
        return faces
    if min_extent / max_extent >= _DIRECTIONAL_ADDPOINT_THIN_RATIO:
        return faces

    collider_center = _collider_center_local(collider=collider)
    outward_vector = collider_center - solid_centroid
    outward_norm = float(np.linalg.norm(outward_vector))
    if outward_norm <= 1e-9:
        return faces
    outward_vector = outward_vector / outward_norm

    best_face = max(
        faces,
        key=lambda item: float(np.dot(item[1], outward_vector)),
    )
    return [best_face]


def _select_steering_hinge_end_face(
    *,
    block_id: int,
    colliders: list[dict[str, Any]],
    faces: list[tuple[np.ndarray, np.ndarray]],
) -> list[tuple[np.ndarray, np.ndarray]]:
    """Select the single free end cap for steering hinge blocks."""
    if block_id not in _STEERING_HINGE_END_ONLY_BLOCK_IDS:
        return faces
    if len(faces) == 0:
        return faces

    start_trigger = None
    end_trigger = None
    for collider in colliders:
        if not _is_joint_trigger_collider(collider=collider):
            continue
        name = str(collider.get("gameobject_name", "")).strip().lower()
        if name == "triggerforjoint":
            start_trigger = _collider_center_local(collider=collider)
        elif name == "triggerforjoint2":
            end_trigger = _collider_center_local(collider=collider)

    if start_trigger is None or end_trigger is None:
        raise ValueError(f"Steering hinge block {block_id} must define TriggerForJoint and TriggerForJoint2.")

    hinge_axis = end_trigger - start_trigger
    hinge_axis_norm = float(np.linalg.norm(hinge_axis))
    if hinge_axis_norm <= 1e-9:
        raise ValueError(f"Steering hinge block {block_id} has coincident joint triggers.")
    hinge_axis = hinge_axis / hinge_axis_norm

    return [
        max(
            faces,
            key=lambda item: (
                float(np.dot(item[1], hinge_axis)),
                float(np.dot(item[0], hinge_axis)),
            ),
        )
    ]


def _normalize_hinge_side_face_centers(
    *,
    block_id: int,
    colliders: list[dict[str, Any]],
    faces: list[tuple[np.ndarray, np.ndarray]],
) -> list[tuple[np.ndarray, np.ndarray]]:
    """Place free-hinge side faces at the midpoint of the hinge axis."""
    if block_id not in _HINGE_MIDPOINT_SIDE_BLOCK_IDS:
        return faces
    if len(faces) == 0:
        return faces

    start_trigger = None
    end_trigger = None
    for collider in colliders:
        if not _is_joint_trigger_collider(collider=collider):
            continue
        name = str(collider.get("gameobject_name", "")).strip().lower()
        if name == "triggerforjoint":
            start_trigger = _collider_center_local(collider=collider)
        elif name == "triggerforjoint2":
            end_trigger = _collider_center_local(collider=collider)

    if start_trigger is None or end_trigger is None:
        raise ValueError(f"Hinge block {block_id} must define TriggerForJoint and TriggerForJoint2.")

    hinge_axis = end_trigger - start_trigger
    hinge_axis_norm = float(np.linalg.norm(hinge_axis))
    if hinge_axis_norm <= 1e-9:
        raise ValueError(f"Hinge block {block_id} has coincident joint triggers.")
    hinge_axis = hinge_axis / hinge_axis_norm
    axis_midpoint = (start_trigger + end_trigger) * 0.5

    normalized_faces = []
    for face_center, face_normal in faces:
        if abs(float(np.dot(face_normal, hinge_axis))) >= 0.9:
            normalized_faces.append((face_center, face_normal))
            continue
        offset_along_axis = np.dot(face_center - axis_midpoint, hinge_axis) * hinge_axis
        normalized_faces.append((face_center - offset_along_axis, face_normal))
    return normalized_faces


def _remove_internal_faces(
    *,
    tagged_faces: list[tuple[int, np.ndarray, np.ndarray]],
) -> list[tuple[np.ndarray, np.ndarray]]:
    """Remove pairs of coincident faces with opposing normals that
    originate from *different* colliders (internal contact interfaces)."""
    n = len(tagged_faces)
    to_remove: set[int] = set()
    for i in range(n):
        if i in to_remove:
            continue
        cid_i, pos_i, norm_i = tagged_faces[i]
        for j in range(i + 1, n):
            if j in to_remove:
                continue
            cid_j, pos_j, norm_j = tagged_faces[j]
            if cid_i == cid_j:
                continue
            if (
                np.linalg.norm(pos_i - pos_j) < _FACE_POS_TOLERANCE
                and np.dot(norm_i, norm_j) < _FACE_NORMAL_THRESHOLD
            ):
                to_remove.add(i)
                to_remove.add(j)
                break
    return [
        (tagged_faces[idx][1], tagged_faces[idx][2])
        for idx in range(n)
        if idx not in to_remove
    ]


def _resolve_degenerate_face_pairs(
    *,
    faces: list[tuple[np.ndarray, np.ndarray]],
    solid_centroid: np.ndarray,
) -> list[tuple[np.ndarray, np.ndarray]]:
    """For coincident opposite-normal face pairs (from zero-thickness sheets),
    keep only the face whose normal points away from the solid body centroid."""
    n = len(faces)
    to_remove: set[int] = set()
    for i in range(n):
        if i in to_remove:
            continue
        pos_i, norm_i = faces[i]
        for j in range(i + 1, n):
            if j in to_remove:
                continue
            pos_j, norm_j = faces[j]
            if (
                np.linalg.norm(pos_i - pos_j) < _FACE_POS_TOLERANCE
                and np.dot(norm_i, norm_j) < _FACE_NORMAL_THRESHOLD
            ):
                direction = pos_i - solid_centroid
                if np.dot(norm_i, direction) >= np.dot(norm_j, direction):
                    to_remove.add(j)
                else:
                    to_remove.add(i)
                break
    return [faces[idx] for idx in range(n) if idx not in to_remove]


_INWARD_COS_THRESHOLD = -0.3
_COPLANAR_POS_TOLERANCE = 0.3
_COPLANAR_NORMAL_TOLERANCE = 0.9
_SKIN_OVERSHOOT_RATIO = 0.5


def _remove_inward_faces(
    *,
    faces: list[tuple[np.ndarray, np.ndarray]],
    reference_centroid: np.ndarray,
) -> list[tuple[np.ndarray, np.ndarray]]:
    """Remove faces whose normal points significantly toward the reference centroid.

    Uses cosine similarity between the face normal and the direction from
    the centroid to the face center.  A face with cos < _INWARD_COS_THRESHOLD
    is classified as interior (pointing into the block body) and removed.
    This generalises the degenerate-pair resolution (zero-thickness sheets)
    AND handles thick addpoint boxes partially embedded in the block.
    """
    result: list[tuple[np.ndarray, np.ndarray]] = []
    for fc, fn in faces:
        direction = fc - reference_centroid
        dist = float(np.linalg.norm(direction))
        if dist < 1e-6:
            result.append((fc, fn))
            continue
        cos_angle = float(np.dot(fn, direction)) / dist
        if cos_angle >= _INWARD_COS_THRESHOLD:
            result.append((fc, fn))
    return result


def _merge_coplanar_faces(
    *,
    faces: list[tuple[np.ndarray, np.ndarray]],
) -> list[tuple[np.ndarray, np.ndarray]]:
    """Merge nearby faces from different colliders that share the same normal.

    When overlapping colliders produce redundant attachment faces at almost
    the same position with the same normal direction, keep only the outermost
    one (the one farthest along its own normal direction).
    """
    n = len(faces)
    to_remove: set[int] = set()
    for i in range(n):
        if i in to_remove:
            continue
        pos_i, norm_i = faces[i]
        for j in range(i + 1, n):
            if j in to_remove:
                continue
            pos_j, norm_j = faces[j]
            if np.dot(norm_i, norm_j) < _COPLANAR_NORMAL_TOLERANCE:
                continue
            if np.linalg.norm(pos_i - pos_j) >= _COPLANAR_POS_TOLERANCE:
                continue
            proj_i = float(np.dot(pos_i, norm_i))
            proj_j = float(np.dot(pos_j, norm_j))
            if proj_i >= proj_j:
                to_remove.add(j)
            else:
                to_remove.add(i)
                break
    return [faces[idx] for idx in range(n) if idx not in to_remove]


_SKIN_OVERSHOOT_FRAC = 0.3


_MESH_SUPPORT_THICKNESS = 0.1
_MESH_SUPPORT_MIN_SPREAD = 0.5
_MESH_BBOX_MARGIN = 0.05
_MESH_BODY_OVERFLOW_THRESHOLD = 0.02


def _box_collider_bounds_local(
    *,
    collider: dict[str, Any],
) -> tuple[np.ndarray, np.ndarray] | None:
    """Axis-aligned bounding box of a box collider in block-local space.

    Returns ``None`` when the collider is non-box or has degenerate
    extents.  This is intentionally axis-aligned: the rotational
    component on the collider is dropped to compute a conservative bbox
    suitable for "is the visual decorating this cube?" checks.
    """
    if collider.get("type") != "box":
        return None
    center = np.asarray(collider.get("center", [0, 0, 0]), dtype=np.float64)
    local_scale = np.asarray(
        collider.get("local_scale", [1, 1, 1]), dtype=np.float64
    )
    size = np.asarray(collider.get("size", [1, 1, 1]), dtype=np.float64)
    local_position = np.asarray(
        collider.get("local_position", [0, 0, 0]), dtype=np.float64
    )
    half_ext = np.abs(size) * np.abs(local_scale) * 0.5
    if float(np.max(half_ext)) <= 1e-9:
        return None
    effective_center = center * local_scale + local_position
    return effective_center - half_ext, effective_center + half_ext


def _union_box_bounds(
    *,
    colliders: list[dict[str, Any]],
) -> tuple[np.ndarray, np.ndarray] | None:
    """Union axis-aligned bbox over all box colliders in *colliders*."""
    mins: list[np.ndarray] = []
    maxs: list[np.ndarray] = []
    for collider in colliders:
        bounds = _box_collider_bounds_local(collider=collider)
        if bounds is None:
            continue
        mins.append(bounds[0])
        maxs.append(bounds[1])
    if not mins:
        return None
    return np.min(np.stack(mins), axis=0), np.max(np.stack(maxs), axis=0)


def _face_inside_mesh_bbox(
    *,
    face_center: np.ndarray,
    mesh_min: np.ndarray,
    mesh_max: np.ndarray,
    margin: float = _MESH_BBOX_MARGIN,
) -> bool:
    """Whether a face center lies within the mesh's axis-aligned bounding box."""
    for axis_index in range(3):
        if face_center[axis_index] < mesh_min[axis_index] - margin:
            return False
        if face_center[axis_index] > mesh_max[axis_index] + margin:
            return False
    return True


def _face_supported_by_mesh(
    *,
    face_center: np.ndarray,
    face_normal: np.ndarray,
    skin_vertices: np.ndarray,
    thickness: float = _MESH_SUPPORT_THICKNESS,
    min_spread: float = _MESH_SUPPORT_MIN_SPREAD,
) -> bool:
    """Check whether the face plane has flat mesh support across its area.

    A cube face has many vertices spread across the perpendicular axes
    while a cylindrical face has vertices clustered along a single
    tangent line.  Faces are well-supported when the perpendicular
    spread of nearby vertices exceeds *min_spread* in BOTH directions.
    """
    axis_index = int(np.argmax(np.abs(face_normal)))
    perp_axes = [item for item in range(3) if item != axis_index]
    distances = (skin_vertices - face_center) @ face_normal
    near_mask = np.abs(distances) <= thickness
    if int(np.sum(near_mask)) < 4:
        return False
    near_verts = skin_vertices[near_mask]
    for perp in perp_axes:
        spread = float(np.max(near_verts[:, perp]) - np.min(near_verts[:, perp]))
        if spread < min_spread:
            return False
    return True


def _remove_unsupported_cube_faces(
    *,
    faces: list[tuple[np.ndarray, np.ndarray]],
    skin_vertices: np.ndarray,
    addpoint_bounds: tuple[np.ndarray, np.ndarray] | None = None,
) -> list[tuple[np.ndarray, np.ndarray]]:
    """Drop faces that fall inside the mesh bounding box but lack flat
    mesh support across their area (e.g. the side faces of a cylindrical
    block whose AddPoint collider is still a cube).

    Faces lying outside the mesh bounding box (typical for wheel/cog
    front joints whose mesh ends short of the conceptual block face)
    are kept as virtual attach points.

    When *addpoint_bounds* are supplied and the visible mesh extends
    beyond those bounds in any direction, the AddPoint cube collider is
    treated as the gameplay body shape and all faces are kept verbatim.
    This protects cubic blocks whose visual mesh is a stylised ornament
    riding on top of an invisible cube collision body
    (e.g. ``SteeringBlock``, ``SpinningBlock``, ``DoubleWoodenBlock``
    which all have visuals that overflow the AddPoint cube), while the
    Decoupler — whose visual matches the cube exactly — still has its
    side faces correctly pruned.
    """
    if skin_vertices is None or len(skin_vertices) == 0:
        return faces
    mesh_min = np.min(skin_vertices, axis=0)
    mesh_max = np.max(skin_vertices, axis=0)

    if addpoint_bounds is not None:
        ap_min, ap_max = addpoint_bounds
        # Count axes along which the visual mesh actually overflows the
        # AddPoint cube.  A purely cylindrical body (e.g. Decoupler) only
        # overflows along its axial direction; a cube body wrapped in a
        # decorative visual (e.g. SteeringBlock, SpinningBlock,
        # DoubleWoodenBlock) overflows in two or more axes.  Requiring
        # ≥ 2 axes therefore distinguishes "cube body with ornaments"
        # from "cylinder body that just sticks out along its axis".
        overflow_axes = 0
        for axis_index in range(3):
            below = mesh_min[axis_index] < ap_min[axis_index] - _MESH_BODY_OVERFLOW_THRESHOLD
            above = mesh_max[axis_index] > ap_max[axis_index] + _MESH_BODY_OVERFLOW_THRESHOLD
            if below or above:
                overflow_axes += 1
        if overflow_axes >= 2:
            return faces

    result: list[tuple[np.ndarray, np.ndarray]] = []
    for face_center, face_normal in faces:
        inside = _face_inside_mesh_bbox(
            face_center=face_center,
            mesh_min=mesh_min,
            mesh_max=mesh_max,
        )
        if not inside:
            result.append((face_center, face_normal))
            continue
        if _face_supported_by_mesh(
            face_center=face_center,
            face_normal=face_normal,
            skin_vertices=skin_vertices,
        ):
            result.append((face_center, face_normal))
    if not result and faces:
        return faces
    return result


def _remove_mechanism_blocked_faces(
    *,
    faces: list[tuple[np.ndarray, np.ndarray]],
    skin_vertices: np.ndarray,
) -> list[tuple[np.ndarray, np.ndarray]]:
    """Remove faces blocked by mechanism geometry extending beyond them.

    Uses two conditions jointly to avoid false positives from outlier
    vertices (e.g. a thin blade edge):
      1. Max-based overshoot ratio > _SKIN_OVERSHOOT_RATIO
      2. Fraction of skin vertices beyond the face > _SKIN_OVERSHOOT_FRAC
    Both must hold for a face to be classified as interior.
    """
    n_verts = len(skin_vertices)
    result: list[tuple[np.ndarray, np.ndarray]] = []
    for fc, fn in faces:
        face_proj = float(np.dot(fc, fn))
        v_proj = skin_vertices @ fn
        skin_range = float(np.max(v_proj) - np.min(v_proj))
        if skin_range < 1e-6:
            result.append((fc, fn))
            continue
        overshoot = float(np.max(v_proj)) - face_proj
        ratio = overshoot / skin_range
        frac_beyond = float(np.sum(v_proj > face_proj)) / n_verts
        if ratio >= _SKIN_OVERSHOOT_RATIO and frac_beyond >= _SKIN_OVERSHOOT_FRAC:
            continue
        result.append((fc, fn))
    return result


def _single_point_face(
    *,
    collider: dict[str, Any],
) -> tuple[np.ndarray, np.ndarray]:
    """Fallback: derive a single (center, normal) pair for non-box colliders."""
    center = _collider_center_local(collider=collider)
    direction = center / (np.linalg.norm(center) + 1e-12)
    dominant_axis = int(np.argmax(np.abs(direction)))
    sign_val = 1.0 if direction[dominant_axis] >= 0 else -1.0
    normal = np.zeros(3)
    normal[dominant_axis] = sign_val
    return center, normal


def _try_load_skin_mesh(
    *,
    block_id: int,
    block_name: str,
    registry_path: Path | None = None,
) -> tuple[np.ndarray, np.ndarray] | None:
    """Try to load the skin mesh, returning (centroid, vertices) or None."""
    try:
        from .mesh_loader import load_aligned_game_mesh
        rp = get_block_registry_path(registry_path=registry_path)
        vt = get_visual_transform(block_id=block_id)
        aligned = load_aligned_game_mesh(
            mesh_key=block_name,
            visual_transform=vt,
            registry_path=rp,
        )
        if aligned is not None:
            centroid = np.asarray(aligned.centroid, dtype=np.float64)
            vertices = np.asarray(aligned.vertices, dtype=np.float64)
            return centroid, vertices
    except Exception:
        pass
    return None


def _snap_and_dedupe_faces(
    *,
    faces: list[tuple[np.ndarray, np.ndarray]],
) -> list[tuple[np.ndarray, np.ndarray]]:
    """Snap face centers to the half-grid and drop duplicates.

    Two faces are considered duplicates when the snapped center coincides
    and the normals point in the same direction (after rounding for
    numerical stability).  Normals are not snapped because face filters
    upstream already enforce axis-alignment.
    """
    deduped: list[tuple[np.ndarray, np.ndarray]] = []
    seen: set[tuple[tuple[float, float, float], tuple[float, float, float]]] = set()
    for fc, fn in faces:
        snapped_fc = _snap_vector_to_half(vector=fc)
        rounded_normal = np.round(fn, decimals=6)
        key = (
            (float(snapped_fc[0]), float(snapped_fc[1]), float(snapped_fc[2])),
            (float(rounded_normal[0]), float(rounded_normal[1]), float(rounded_normal[2])),
        )
        if key in seen:
            continue
        seen.add(key)
        deduped.append((snapped_fc, fn))
    return deduped


def _expand_segmented_addpoint_faces(
    *,
    collider: dict[str, Any],
    faces: list[tuple[np.ndarray, np.ndarray]],
) -> list[tuple[np.ndarray, np.ndarray]]:
    """Split long AddPoint sheets into multiple unit-spaced attach centers.

    Some prefabs encode several gameplay attach points as one elongated
    AddPoint plane.  The normal still comes from the AddPoint plane, but the
    centers need to be sampled along the long in-plane axis before snapping.
    """
    if len(faces) == 0:
        return faces
    if str(collider.get("type", "")).strip().lower() != "box":
        return faces
    layer_name = str(collider.get("layer_name", "")).strip().lower()
    if layer_name != "addpoint":
        return faces

    size = np.asarray(collider.get("size", [1, 1, 1]), dtype=np.float64)
    local_scale = np.asarray(collider.get("local_scale", [1, 1, 1]), dtype=np.float64)
    extents = np.abs(size * local_scale)
    long_axis = int(np.argmax(extents))
    long_extent = float(extents[long_axis])
    if long_extent < 2.0:
        return faces

    # Split only one-dimensional strips.  Broad 2D AddPoint sheets are already
    # represented by separate colliders where the game exposes separate points.
    nonzero_axes = [axis for axis, extent in enumerate(extents) if float(extent) > 1e-6]
    if len(nonzero_axes) != 2:
        return faces
    short_axes = [axis for axis in nonzero_axes if axis != long_axis]
    if len(short_axes) != 1:
        return faces
    if float(extents[short_axes[0]]) > 1.1:
        return faces

    rot_mat = _rotation_matrix_from_wxyz(
        local_rotation=collider.get("local_rotation", [1, 0, 0, 0])
    )
    offsets = [-1.0, 0.0, 1.0]
    result: list[tuple[np.ndarray, np.ndarray]] = []
    for face_center, face_normal in faces:
        for offset_value in offsets:
            offset_local = np.zeros(3, dtype=np.float64)
            offset_local[long_axis] = offset_value
            result.append((face_center + rot_mat @ offset_local, face_normal))
    return result


def _infer_faces_for_role(
    *,
    block_id: int,
    shape: list[float] | np.ndarray,
    role: str,
    dump_path: Path | None = None,
    registry_path: Path | None = None,
) -> dict[str, dict[str, list[float] | str]] | None:
    dump = load_dump(dump_path=dump_path)
    block_entry = dump.get(block_id)
    if block_entry is None:
        return None
    block_name = str(block_entry.get("name", ""))
    if not _block_is_enabled(block_id=block_id, block_name=block_name):
        return None

    colliders = block_entry.get("colliders", [])
    if len(colliders) == 0:
        return None

    shape_arr = np.asarray(shape, dtype=np.float64)
    safe_shape = np.where(np.abs(shape_arr) < 1e-9, 1.0, shape_arr)

    filtered_colliders = [c for c in colliders if not _is_noise_collider(collider=c)]

    if role == "addpoint":
        if block_id in _NO_ADDPOINT_FACE_BLOCK_IDS:
            return None
        candidate_colliders = [
            c for c in filtered_colliders if _is_add_point_collider(collider=c)
        ]
    elif role == "joint":
        candidate_colliders = [
            c for c in filtered_colliders if _is_joint_trigger_collider(collider=c)
        ]
    else:
        raise ValueError(f"Unsupported face role '{role}'")

    if len(candidate_colliders) == 0:
        return None

    if role == "addpoint":
        tagged_faces: list[tuple[int, np.ndarray, np.ndarray]] = []
        solid_centers: list[np.ndarray] = []
        for c in colliders:
            if not c.get("enabled", True):
                continue
            if bool(c.get("is_trigger", False)):
                continue
            if _is_noise_collider(collider=c):
                continue
            solid_centers.append(_collider_center_local(collider=c))
        solid_centroid = np.mean(solid_centers, axis=0) if len(solid_centers) > 0 else None

        for cid, collider in enumerate(candidate_colliders):
            if collider.get("type") == "box":
                collider_faces = _enumerate_box_faces(collider=collider)
                collider_faces = _select_outward_named_addpoint_faces(
                    collider=collider,
                    faces=collider_faces,
                    solid_centroid=solid_centroid,
                )
                collider_faces = _expand_segmented_addpoint_faces(
                    collider=collider,
                    faces=collider_faces,
                )
                for fc, fn in collider_faces:
                    tagged_faces.append((cid, fc, fn))
            else:
                fc, fn = _single_point_face(collider=collider)
                tagged_faces.append((cid, fc, fn))

        external_faces = _remove_internal_faces(tagged_faces=tagged_faces)
        external_faces = _normalize_hinge_side_face_centers(
            block_id=block_id,
            colliders=colliders,
            faces=external_faces,
        )
        external_faces = _select_steering_hinge_end_face(
            block_id=block_id,
            colliders=colliders,
            faces=external_faces,
        )
        full_cube_addpoint_faces = (
            list(external_faces)
            if block_id in _FULL_CUBE_ADDPOINT_BLOCK_IDS
            else None
        )

        skin_data = _try_load_skin_mesh(
            block_id=block_id,
            block_name=block_name,
            registry_path=registry_path,
        )
        if skin_data is not None:
            skin_centroid, skin_vertices = skin_data
            external_faces = _remove_inward_faces(
                faces=external_faces,
                reference_centroid=skin_centroid,
            )
            external_faces = _merge_coplanar_faces(faces=external_faces)
            external_faces = _remove_mechanism_blocked_faces(
                faces=external_faces,
                skin_vertices=skin_vertices,
            )
            external_faces = _remove_unsupported_cube_faces(
                faces=external_faces,
                skin_vertices=skin_vertices,
                addpoint_bounds=_union_box_bounds(
                    colliders=candidate_colliders
                ),
            )
            if full_cube_addpoint_faces is not None:
                external_faces = full_cube_addpoint_faces
        else:
            if len(solid_centers) > 0:
                solid_centroid = np.mean(solid_centers, axis=0)
                external_faces = _resolve_degenerate_face_pairs(
                    faces=external_faces,
                    solid_centroid=solid_centroid,
                )
            external_faces = _merge_coplanar_faces(faces=external_faces)

        snapped_faces = _snap_and_dedupe_faces(faces=external_faces)
        faces: dict[str, dict[str, list[float] | str]] = {}
        for idx, (fc, fn) in enumerate(snapped_faces):
            rel_pos = (fc / safe_shape).tolist()
            faces[f"f{idx}"] = {
                "rel_pos": [float(v) for v in rel_pos],
                "normal": [float(v) for v in fn.tolist()],
                "role": "addpoint",
            }
        return faces if len(faces) > 0 else None

    raw_faces: list[tuple[np.ndarray, np.ndarray]] = []
    for collider in candidate_colliders:
        fc, fn = _single_point_face(collider=collider)
        raw_faces.append((fc, fn))
    snapped_faces = _snap_and_dedupe_faces(faces=raw_faces)

    faces = {}
    for idx, (fc, fn) in enumerate(snapped_faces):
        rel_pos = (fc / safe_shape).tolist()
        faces[f"f{idx}"] = {
            "rel_pos": [float(v) for v in rel_pos],
            "normal": [float(v) for v in fn.tolist()],
            "role": role,
        }
    return faces if len(faces) > 0 else None


def compute_root_offset(
    *,
    block_id: int,
    vec_base: list[float] | np.ndarray | None = None,
    dump_path: Path | None = None,
) -> float:
    """Compute placement offset for blocks whose connecting face is below the local origin.

    Returns the distance along *vec_base* that ``geo.position`` must be pushed
    outward from the base face so the connecting face aligns with it.
    A positive value means the block needs to be shifted away from the base.
    Returns 0.0 when no adjustment is needed.
    """
    if vec_base is None:
        vec_base = [0.0, 0.0, 1.0]
    vb = np.asarray(vec_base, dtype=np.float64)
    vb_norm = vb / (np.linalg.norm(vb) + 1e-12)
    target_normal = -vb_norm

    colliders = get_colliders_for_block(block_id=block_id, dump_path=dump_path)
    if colliders is None:
        return 0.0

    filtered = [c for c in colliders if not _is_noise_collider(collider=c)]
    candidates = [c for c in filtered if _is_add_point_collider(collider=c)]
    if not candidates:
        return 0.0

    best_face_z: float | None = None

    for c in candidates:
        if c.get("type") == "box":
            faces = _enumerate_box_faces(collider=c)
        else:
            faces = [_single_point_face(collider=c)]
        for fc, fn in faces:
            fn_hat = fn / (np.linalg.norm(fn) + 1e-12)
            cos_val = float(np.dot(fn_hat, target_normal))
            if cos_val > 0.7:
                face_z = float(np.dot(fc, vb_norm))
                if best_face_z is None or face_z < best_face_z:
                    best_face_z = face_z

    if best_face_z is not None and best_face_z < -0.01:
        return -best_face_z
    return 0.0


def infer_addpoint_faces_from_dump(*, block_id: int, shape: list[float] | np.ndarray, dump_path: Path | None = None, registry_path: Path | None = None) -> dict[str, dict[str, list[float] | str]] | None:
    return _infer_faces_for_role(block_id=block_id, shape=shape, role="addpoint", dump_path=dump_path, registry_path=registry_path)


def infer_joint_faces_from_dump(*, block_id: int, shape: list[float] | np.ndarray, dump_path: Path | None = None, registry_path: Path | None = None) -> dict[str, dict[str, list[float] | str]] | None:
    return _infer_faces_for_role(block_id=block_id, shape=shape, role="joint", dump_path=dump_path, registry_path=registry_path)


def infer_faces_from_dump(*, block_id: int, shape: list[float] | np.ndarray, dump_path: Path | None = None, registry_path: Path | None = None) -> dict[str, dict[str, list[float] | str]] | None:
    """Backward-compatible wrapper: prefer addpoint, fallback to joint."""
    addpoint = infer_addpoint_faces_from_dump(block_id=block_id, shape=shape, dump_path=dump_path, registry_path=registry_path)
    if addpoint is not None:
        return addpoint
    return infer_joint_faces_from_dump(block_id=block_id, shape=shape, dump_path=dump_path, registry_path=registry_path)


def build_attachable_face_report(*, include_disabled: bool = False, dump_path: Path | None = None) -> str:
    """Return a text report of inferred addpoint/joint faces for all blocks."""
    dump = load_dump(dump_path=dump_path)
    lines: list[str] = []
    lines.append("Attachable Face Report (dump-derived)")
    lines.append("role(addpoint)=attachable, role(joint)=connector probe")
    lines.append("")

    for block_id in sorted(dump.keys()):
        entry = dump[block_id]
        block_name = str(entry.get("name", f"id-{block_id}"))
        enabled = _block_is_enabled(block_id=block_id, block_name=block_name)
        if not include_disabled and not enabled:
            continue

        add_faces = infer_addpoint_faces_from_dump(block_id=block_id, shape=[1.0, 1.0, 1.0], dump_path=dump_path) or {}
        joint_faces = infer_joint_faces_from_dump(block_id=block_id, shape=[1.0, 1.0, 1.0], dump_path=dump_path) or {}

        lines.append(f"[{block_id}] {block_name}  enabled={enabled}")
        lines.append(f"  addpoint_faces={len(add_faces)}  joint_faces={len(joint_faces)}")

        for label, face in add_faces.items():
            rel_pos = np.asarray(face["rel_pos"], dtype=np.float64)
            normal = np.asarray(face["normal"], dtype=np.float64)
            lines.append(
                "    addpoint {label}: rel_pos={rp} normal={nm}".format(
                    label=label,
                    rp=np.array2string(rel_pos, precision=4, separator=",", suppress_small=True),
                    nm=np.array2string(normal, precision=4, separator=",", suppress_small=True),
                )
            )
        for label, face in joint_faces.items():
            rel_pos = np.asarray(face["rel_pos"], dtype=np.float64)
            normal = np.asarray(face["normal"], dtype=np.float64)
            lines.append(
                "    joint    {label}: rel_pos={rp} normal={nm}".format(
                    label=label,
                    rp=np.array2string(rel_pos, precision=4, separator=",", suppress_small=True),
                    nm=np.array2string(normal, precision=4, separator=",", suppress_small=True),
                )
            )
        lines.append("")

    return "\n".join(lines)


def _rotation_matrix_from_wxyz(*, local_rotation: list[float]) -> np.ndarray:
    quat = nq.quaternion(
        local_rotation[0],
        local_rotation[1],
        local_rotation[2],
        local_rotation[3],
    ).normalized()
    return nq.as_rotation_matrix(quat)


def _apply_dump_transform(
    *,
    mesh: trimesh.Trimesh,
    scaled_center: np.ndarray,
    local_position: list[float],
    local_rotation: list[float],
) -> trimesh.Trimesh:
    rot_mat = _rotation_matrix_from_wxyz(local_rotation=local_rotation)
    offset = rot_mat @ scaled_center + np.asarray(local_position, dtype=np.float64)
    transform = np.eye(4, dtype=np.float64)
    transform[:3, :3] = rot_mat
    transform[:3, 3] = offset
    mesh.apply_transform(transform)
    return mesh


def _build_collider_from_dump(*, collider: dict[str, Any]) -> trimesh.Trimesh | None:
    ctype = collider.get("type", "")
    local_position = collider.get("local_position", [0, 0, 0])
    local_rotation = collider.get("local_rotation", [1, 0, 0, 0])
    local_scale = np.asarray(collider.get("local_scale", [1, 1, 1]), dtype=np.float64)
    center = np.asarray(collider.get("center", [0, 0, 0]), dtype=np.float64)

    if ctype == "box":
        size = np.asarray(collider["size"], dtype=np.float64)
        mesh = trimesh.creation.box(extents=size * local_scale)
        return _apply_dump_transform(
            mesh=mesh,
            scaled_center=center * local_scale,
            local_position=local_position,
            local_rotation=local_rotation,
        )

    if ctype == "sphere":
        radius = float(collider["radius"])
        effective_radius = radius * float(np.max(local_scale))
        mesh = trimesh.creation.icosphere(radius=effective_radius, subdivisions=2)
        return _apply_dump_transform(
            mesh=mesh,
            scaled_center=center * local_scale,
            local_position=local_position,
            local_rotation=local_rotation,
        )

    if ctype == "capsule":
        direction = int(collider.get("direction", 1))
        radius = float(collider["radius"])
        height = float(collider["height"])

        dir_scale = float(local_scale[direction])
        perp_scale = float(np.max(np.delete(local_scale, direction)))
        effective_height = height * dir_scale
        effective_radius = radius * perp_scale

        mesh = trimesh.creation.capsule(
            height=max(effective_height - 2 * effective_radius, 0.0),
            radius=effective_radius,
        )

        if direction == 0:
            align = trimesh.transformations.rotation_matrix(np.pi / 2, [0, 1, 0])
            mesh.apply_transform(align)
        elif direction == 1:
            align = trimesh.transformations.rotation_matrix(-np.pi / 2, [1, 0, 0])
            mesh.apply_transform(align)

        return _apply_dump_transform(
            mesh=mesh,
            scaled_center=center * local_scale,
            local_position=local_position,
            local_rotation=local_rotation,
        )

    return None


def build_collider_mesh(*, block_id: int, solid_only: bool = True, dump_path: Path | None = None) -> trimesh.Trimesh | None:
    """Build a combined trimesh for all colliders of a block."""
    colliders = get_colliders_for_block(block_id=block_id, dump_path=dump_path)
    if colliders is None:
        return None

    parts: list[trimesh.Trimesh] = []
    for collider in colliders:
        if not collider.get("enabled", True):
            continue
        if solid_only and collider.get("is_trigger", False):
            continue

        collider_mesh = _build_collider_from_dump(collider=collider)
        if collider_mesh is not None:
            parts.append(collider_mesh)

    if not parts:
        return None

    return trimesh.util.concatenate(parts)
